<?php

declare (strict_types=1);
namespace Laminas\Mvc\Controller\Plugin;

use function array_shift;
use function get_debug_type;
use function is_array;
use function is_object;
use Laminas\Event_Manager\Shared_Event_Manager_Interface as SharedEvents;
use Laminas\Mvc\Controller\Controller_Manager;
use Laminas\Mvc\Exception;
use Laminas\Mvc\Exception\DomainException;
use Laminas\Mvc\Inject_Application_Event_Interface;
use Laminas\Mvc\Mvc_Event;
use Laminas\Mvc\View\Http\Inject_View_Model_Listener;
use Laminas\Router\Route_Match;
use Laminas\Stdlib\Callback_Handler;
use Laminas\Stdlib\Dispatchable_Interface;
use function sprintf;
use Traversable;
class Forward extends Abstract_Plugin
{
    /** @var MvcEvent */
    protected $event;
    /** @var int */
    protected $max_nested_forwards = 10;
    /** @var int */
    protected $num_nested_forwards = 0;
    /** @var array[]|null */
    protected $listeners_to_detach;
    public function __construct(protected Controller_Manager $controllers)
    {
    }
    /**
     * Set maximum number of nested forwards allowed
     *
     * @param  int $maxNestedForwards
     */
    public function set_max_nested_forwards($max_nested_forwards): static
    {
        $this->max_nested_forwards = (int) $max_nested_forwards;
        return $this;
    }
    /**
     * Get information on listeners that need to be detached before dispatching.
     *
     * Each entry in the array contains three keys:
     *
     * id (identifier for event-emitting component),
     * event (the hooked event)
     * and class (the class of listener that should be detached).
     *
     * @return array
     */
    public function get_listeners_to_detach()
    {
        // If a blacklist has not been explicitly set, return the default:
        if (null === $this->listeners_to_detach) {
            // We need to detach the InjectViewModelListener to prevent templates
            // from getting attached to the ViewModel twice when a calling action
            // returns the output generated by a forwarded action.
            $this->listeners_to_detach = [['id' => Dispatchable_Interface::class, 'event' => Mvc_Event::EVENT_DISPATCH, 'class' => Inject_View_Model_Listener::class]];
        }
        return $this->listeners_to_detach;
    }
    /**
     * Set information on listeners that need to be detached before dispatching.
     *
     * @param  array $listeners Listener information; see getListenersToDetach() for details on format.
     */
    public function set_listeners_to_detach($listeners): static
    {
        $this->listeners_to_detach = $listeners;
        return $this;
    }
    /**
     * Dispatch another controller
     *
     * @param  string $name Controller name; either a class name or an alias used in the controller manager
     * @param  null|array $params Parameters with which to seed a custom RouteMatch object for the new controller
     * @return mixed
     * @throws Exception\DomainException If composed controller does not define InjectApplicationEventInterface
     *         or Locator aware; or if the discovered controller is not dispatchable.
     */
    public function dispatch($name, ?array $params = null)
    {
        $event = clone $this->get_event();
        $controller = $this->controllers->get($name);
        if ($controller instanceof Inject_Application_Event_Interface) {
            $controller->set_event($event);
        }
        // Allow passing parameters to seed the RouteMatch with & copy matched route name
        if ($params !== null) {
            $route_match = new Route_Match($params);
            $route_match->set_matched_route_name($event->get_route_match()->get_matched_route_name());
            $event->set_route_match($route_match);
        }
        if ($this->num_nested_forwards > $this->max_nested_forwards) {
            throw new DomainException("Circular forwarding detected: greater than {$this->max_nested_forwards} nested forwards");
        }
        $this->num_nested_forwards++;
        // Detach listeners that may cause problems during dispatch:
        $shared_events = $event->get_application()->get_event_manager()->get_shared_manager();
        $listeners = $this->detach_problem_listeners($shared_events);
        $return = $controller->dispatch($event->get_request(), $event->get_response());
        // If we detached any listeners, reattach them now:
        $this->reattach_problem_listeners($shared_events, $listeners);
        $this->num_nested_forwards--;
        return $return;
    }
    /**
     * Detach problem listeners specified by getListenersToDetach() and return an array of information that will
     * allow them to be reattached.
     *
     * @param  SharedEvents $sharedEvents Shared event manager
     */
    protected function detach_problem_listeners(Shared_Events $shared_events): array
    {
        // Convert the problem list from two-dimensional array to more convenient id => event => class format:
        $formatted_problems = [];
        foreach ($this->get_listeners_to_detach() as $current) {
            if (!isset($formatted_problems[$current['id']])) {
                $formatted_problems[$current['id']] = [];
            }
            if (!isset($formatted_problems[$current['id']][$current['event']])) {
                $formatted_problems[$current['id']][$current['event']] = [];
            }
            $formatted_problems[$current['id']][$current['event']][] = $current['class'];
        }
        // Loop through the class blacklist, detaching problem events and remembering their CallbackHandlers
        // for future reference:
        $results = [];
        foreach ($formatted_problems as $id => $event_array) {
            $results[$id] = [];
            foreach ($event_array as $event_name => $class_array) {
                $results[$id][$event_name] = [];
                $events = $this->get_shared_listeners_by_id($id, $event_name, $shared_events);
                foreach ($events as $priority => $current_priority_events) {
                    foreach ($current_priority_events as $current_event) {
                        $current_callback = $current_event;
                        // If we have an array, grab the object
                        if (is_array($current_callback)) {
                            $current_callback = array_shift($current_callback);
                        }
                        // This routine is only valid for object callbacks
                        if (!is_object($current_callback)) {
                            continue;
                        }
                        foreach ($class_array as $class) {
                            if ($current_callback instanceof $class) {
                                $this->detach_shared_listener($id, $current_event, $shared_events);
                                $results[$id][$event_name][$priority] = $current_event;
                            }
                        }
                    }
                }
            }
        }
        return $results;
    }
    /**
     * Reattach all problem listeners detached by detachProblemListeners(), if any.
     *
     * @param  SharedEvents $sharedEvents Shared event manager
     * @param  array        $listeners    Output of detachProblemListeners()
     * @return void
     */
    protected function reattach_problem_listeners(Shared_Events $shared_events, array $listeners)
    {
        foreach ($listeners as $id => $event_array) {
            foreach ($event_array as $event_name => $callbacks) {
                foreach ($callbacks as $priority => $current) {
                    $callback = $current;
                    $shared_events->attach($id, $event_name, $callback, $priority);
                }
            }
        }
    }
    /**
     * Get the event
     *
     * @return MvcEvent
     * @throws Exception\DomainException If unable to find event.
     */
    protected function get_event()
    {
        if ($this->event) {
            return $this->event;
        }
        $controller = $this->get_controller();
        if (!$controller instanceof Inject_Application_Event_Interface) {
            throw new DomainException(sprintf('Forward plugin requires a controller that implements InjectApplicationEventInterface; received %s', get_debug_type($controller)));
        }
        $event = $controller->get_event();
        if (!$event instanceof Mvc_Event) {
            $params = [];
            if ($event) {
                $params = $event->get_params();
            }
            $event = new Mvc_Event();
            $event->set_params($params);
        }
        $this->event = $event;
        return $this->event;
    }
    /**
     * Retrieve shared listeners for an event by identifier.
     *
     * Varies retrieval based on laminas-eventmanager version.
     *
     * @param string $event
     * @return array|Traversable
     */
    private function get_shared_listeners_by_id(int|string $id, int|string $event, Shared_Events $shared_events)
    {
        return $shared_events->get_listeners([$id], $event);
    }
    /**
     * Detach a shared listener by identifier.
     *
     * Varies detachment based on laminas-eventmanager version.
     *
     * @param callable|CallbackHandler $listener
     */
    private function detach_shared_listener(int|string $id, $listener, Shared_Events $shared_events): void
    {
        $shared_events->detach($listener, $id);
    }
}